# Generated by Django 5.0.4 on 2024-04-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_recipe_allergens_recipe_ingredients"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["created_at"], name="polls_recip_created_b45522_idx"
            ),
        ),
    ]
